## NumPy Basics 2.1

In [1]:
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


### Vectors and Matrics

In [3]:
vec = np.array([1,2,3])
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(vec,'\n')
print(mat,'\n')
print(mat.T)

[1 2 3] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [4]:
vec2 = np.arange(0,15)
print(vec2)
vec3 = np.arange(3,17,3)
print(vec3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 3  6  9 12 15]


In [5]:
vec4 = np.linspace(0,5,10)
print(vec4,'\n')
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped,'\n')
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ] 

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]] 

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [6]:
mat2 = np.zeros([5,3])
print(mat2,'\n')
mat3 = np.ones((3,5)) #either we can use [] or () both are fine
print(mat3,'\n')
mat4 = np.eye(5) #identity matrix
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Operations:

In [7]:
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [8]:
#Matrix multiplication
print(mat,'\n')
print(vec,'\n')
product = np.matmul(mat,vec)
print(product)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3] 

[14 32 50]


In [9]:
# Need to check
print(np.linalg.solve(mat,product),'\n')
print(np.linalg.inv(mat))

[-0.8  5.6  1.2] 

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [10]:
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
vec7_1 = np.array([1,5,2,6,8,6])
print(vec7)
print(vec7_1)
print (np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
[1 5 2 6 8 6]
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [11]:
rand_mat = np.random.rand(5,5)
print(rand_mat,'\n')
rand_mat2 = np.random.randn(10,5)
print(rand_mat2,'\n')

[[0.06980965 0.04332432 0.48453441 0.37258624 0.77987981]
 [0.05728532 0.48789538 0.42652687 0.00243639 0.14433355]
 [0.88163496 0.44024458 0.28692008 0.94286271 0.63568482]
 [0.32316457 0.57502597 0.16066403 0.69679869 0.3183468 ]
 [0.48129762 0.21583251 0.71351631 0.61757222 0.58746028]] 

[[-0.52086723  0.0945049   1.17048834  0.72856192 -0.1829605 ]
 [ 0.56310221  1.23458427 -0.70012184  2.12617157 -0.79454001]
 [-0.09638831 -0.10884355 -1.28286347  0.89149078  0.31429159]
 [ 0.22397172 -1.14553707  0.79022081  1.07603243 -0.69624794]
 [ 0.14376004  0.12432375 -0.0763623  -0.42264716  0.93901336]
 [-0.24966372  0.21109868  0.43316208  0.76139025 -2.15366072]
 [-1.18164541 -0.84471025  0.38369433  0.21937084 -0.84149525]
 [ 0.84014711  2.22058366 -1.88895698 -1.97971284  1.06503851]
 [ 0.80850547 -0.91722305 -1.28738613 -1.36830142  0.25156219]
 [ 1.1430072   1.1193079  -1.49511273 -0.12182598  0.59615279]] 



In [12]:
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.42982552350782255
1.0002698171172453


In [13]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.00243638845862737
2.2205836646409898


## NumPy Basics 2.2

In [14]:
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[2]) #vector can be accessible by indexes

[-1.82595582  0.74500285  0.31284754 -2.00817771  0.36091951  0.43292024
 -1.28885304 -0.10818301 -0.44481122 -1.52179405  0.31626582  2.27437866
  0.36370106  0.89088296 -1.50238669 -0.59130893  0.06513794 -1.34009672
 -1.58010394]
0.31284754439457024


In [15]:
#We can access multiple entries at once using :
print(rand_vec[4:9]) # where 4-> inclusive and 9->Exclusive

[ 0.36091951  0.43292024 -1.28885304 -0.10818301 -0.44481122]


In [16]:
# Access multiple non-consucutive entries
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[-1.82595582 -2.00817771 -1.28885304 -1.52179405  0.36370106]


In [17]:
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])

[[0.06980965 0.04332432 0.48453441 0.37258624 0.77987981]
 [0.05728532 0.48789538 0.42652687 0.00243639 0.14433355]
 [0.88163496 0.44024458 0.28692008 0.94286271 0.63568482]
 [0.32316457 0.57502597 0.16066403 0.69679869 0.3183468 ]
 [0.48129762 0.21583251 0.71351631 0.61757222 0.58746028]]
0.42652687157151226
0.42652687157151226


In [18]:
print(rand_mat[0:2,1:3]) # submatrics can also be accessible

[[0.04332432 0.48453441]
 [0.48789538 0.42652687]]


In [19]:
# Lets changes some values in array
print(rand_vec,'\n')
rand_vec[3:5] = 4

print(rand_vec,'\n')
rand_vec[3:5] = [1,2]
print(rand_vec)


[-1.82595582  0.74500285  0.31284754 -2.00817771  0.36091951  0.43292024
 -1.28885304 -0.10818301 -0.44481122 -1.52179405  0.31626582  2.27437866
  0.36370106  0.89088296 -1.50238669 -0.59130893  0.06513794 -1.34009672
 -1.58010394] 

[-1.82595582  0.74500285  0.31284754  4.          4.          0.43292024
 -1.28885304 -0.10818301 -0.44481122 -1.52179405  0.31626582  2.27437866
  0.36370106  0.89088296 -1.50238669 -0.59130893  0.06513794 -1.34009672
 -1.58010394] 

[-1.82595582  0.74500285  0.31284754  1.          2.          0.43292024
 -1.28885304 -0.10818301 -0.44481122 -1.52179405  0.31626582  2.27437866
  0.36370106  0.89088296 -1.50238669 -0.59130893  0.06513794 -1.34009672
 -1.58010394]


In [20]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)


[[0.06980965 0.04332432 0.48453441 0.37258624 0.77987981]
 [0.05728532 0.48789538 0.42652687 0.00243639 0.14433355]
 [0.88163496 0.44024458 0.28692008 0.94286271 0.63568482]
 [0.32316457 0.57502597 0.16066403 0.69679869 0.3183468 ]
 [0.48129762 0.21583251 0.71351631 0.61757222 0.58746028]]

[[0.06980965 0.04332432 0.48453441 0.37258624 0.77987981]
 [0.05728532 0.48789538 0.42652687 0.         0.        ]
 [0.88163496 0.44024458 0.28692008 0.         0.        ]
 [0.32316457 0.57502597 0.16066403 0.69679869 0.3183468 ]
 [0.48129762 0.21583251 0.71351631 0.61757222 0.58746028]]


In [21]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.06980965 0.04332432 0.48453441]
 [0.05728532 0.48789538 0.42652687]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [22]:
print(rand_mat)

[[3.         3.         3.         0.37258624 0.77987981]
 [3.         3.         3.         0.         0.        ]
 [0.88163496 0.44024458 0.28692008 0.         0.        ]
 [0.32316457 0.57502597 0.16066403 0.69679869 0.3183468 ]
 [0.48129762 0.21583251 0.71351631 0.61757222 0.58746028]]


In [23]:
sub_mat2 = rand_mat[0:2,0:3].copy()
print(sub_mat2,'\n')
sub_mat2[:] = 99
print(sub_mat2,'\n')
print(rand_mat)

[[3. 3. 3.]
 [3. 3. 3.]] 

[[99. 99. 99.]
 [99. 99. 99.]] 

[[3.         3.         3.         0.37258624 0.77987981]
 [3.         3.         3.         0.         0.        ]
 [0.88163496 0.44024458 0.28692008 0.         0.        ]
 [0.32316457 0.57502597 0.16066403 0.69679869 0.3183468 ]
 [0.48129762 0.21583251 0.71351631 0.61757222 0.58746028]]


In [24]:
#Asked in non-graded McQ
p1 = np.arange(10,20)
p2 = p1[np.arange(0,10,3)]
print(p2)

[10 13 16 19]


## NumPy Basics 2.3

In [25]:
#access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec,'\n')
print(rand_vec>0,'\n') #this will return true and false
print(rand_vec[rand_vec > 0]) #This will retrun the result array which has values Greater than Zero

[ 1.44277983  0.28503724 -1.84555373  0.52226151 -0.13733371  0.34014607
 -0.51928412 -1.39766569 -1.65281561  1.13679774  0.7522295   0.94342316
 -1.49640826 -0.31897516 -0.64321265] 

[ True  True False  True False  True False False False  True  True  True
 False False False] 

[1.44277983 0.28503724 0.52226151 0.34014607 1.13679774 0.7522295
 0.94342316]


In [26]:
#lets verify the same on matrices
print(rand_mat2,'\n')
print(rand_mat2[rand_mat2>0])

[[-0.52086723  0.0945049   1.17048834  0.72856192 -0.1829605 ]
 [ 0.56310221  1.23458427 -0.70012184  2.12617157 -0.79454001]
 [-0.09638831 -0.10884355 -1.28286347  0.89149078  0.31429159]
 [ 0.22397172 -1.14553707  0.79022081  1.07603243 -0.69624794]
 [ 0.14376004  0.12432375 -0.0763623  -0.42264716  0.93901336]
 [-0.24966372  0.21109868  0.43316208  0.76139025 -2.15366072]
 [-1.18164541 -0.84471025  0.38369433  0.21937084 -0.84149525]
 [ 0.84014711  2.22058366 -1.88895698 -1.97971284  1.06503851]
 [ 0.80850547 -0.91722305 -1.28738613 -1.36830142  0.25156219]
 [ 1.1430072   1.1193079  -1.49511273 -0.12182598  0.59615279]] 

[0.0945049  1.17048834 0.72856192 0.56310221 1.23458427 2.12617157
 0.89149078 0.31429159 0.22397172 0.79022081 1.07603243 0.14376004
 0.12432375 0.93901336 0.21109868 0.43316208 0.76139025 0.38369433
 0.21937084 0.84014711 2.22058366 1.06503851 0.80850547 0.25156219
 1.1430072  1.1193079  0.59615279]


In [27]:
#Lets update the values 
print(rand_vec,'\n')
rand_vec[rand_vec>0.5] = -5
print(rand_vec,'\n')


[ 1.44277983  0.28503724 -1.84555373  0.52226151 -0.13733371  0.34014607
 -0.51928412 -1.39766569 -1.65281561  1.13679774  0.7522295   0.94342316
 -1.49640826 -0.31897516 -0.64321265] 

[-5.          0.28503724 -1.84555373 -5.         -0.13733371  0.34014607
 -0.51928412 -1.39766569 -1.65281561 -5.         -5.         -5.
 -1.49640826 -0.31897516 -0.64321265] 



In [28]:
#Lets save numPy array to the disk to use it later
# there are 2 ways by which we can save
# 1: using this we can save only 1 file

np.save('saved_file_name',rand_mat2)

# saved_file_name.npy: this is extention by which file is saved in workspace

In [29]:
# 2: using this we can save multiple file, Z here is zippped file 
# rand_mat_content & rand_mat_content2 = name of the file we want to define in save_zipped_file
# rand_mat & rand_mat2 are the actual matrices that we are saving within it

np.savez('save_zipped_file',rand_mat_content = rand_mat, rand_mat_content2 = rand_mat2)

# save_zipped_file.npz: this is extention by which file is saved in workspace

In [30]:
# Lets load the files now
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('save_zipped_file.npz')
print(loaded_vec,'\n')
print(loaded_zip,'\n') #will get some weired output for file location

[[-0.52086723  0.0945049   1.17048834  0.72856192 -0.1829605 ]
 [ 0.56310221  1.23458427 -0.70012184  2.12617157 -0.79454001]
 [-0.09638831 -0.10884355 -1.28286347  0.89149078  0.31429159]
 [ 0.22397172 -1.14553707  0.79022081  1.07603243 -0.69624794]
 [ 0.14376004  0.12432375 -0.0763623  -0.42264716  0.93901336]
 [-0.24966372  0.21109868  0.43316208  0.76139025 -2.15366072]
 [-1.18164541 -0.84471025  0.38369433  0.21937084 -0.84149525]
 [ 0.84014711  2.22058366 -1.88895698 -1.97971284  1.06503851]
 [ 0.80850547 -0.91722305 -1.28738613 -1.36830142  0.25156219]
 [ 1.1430072   1.1193079  -1.49511273 -0.12182598  0.59615279]] 




In [31]:
# To load the zip file properly we should do following way

print(loaded_zip['rand_mat_content'],'\n')
print(loaded_zip['rand_mat_content2'],'\n')

new_array = loaded_zip['rand_mat_content']
print(new_array)


[[3.         3.         3.         0.37258624 0.77987981]
 [3.         3.         3.         0.         0.        ]
 [0.88163496 0.44024458 0.28692008 0.         0.        ]
 [0.32316457 0.57502597 0.16066403 0.69679869 0.3183468 ]
 [0.48129762 0.21583251 0.71351631 0.61757222 0.58746028]] 

[[-0.52086723  0.0945049   1.17048834  0.72856192 -0.1829605 ]
 [ 0.56310221  1.23458427 -0.70012184  2.12617157 -0.79454001]
 [-0.09638831 -0.10884355 -1.28286347  0.89149078  0.31429159]
 [ 0.22397172 -1.14553707  0.79022081  1.07603243 -0.69624794]
 [ 0.14376004  0.12432375 -0.0763623  -0.42264716  0.93901336]
 [-0.24966372  0.21109868  0.43316208  0.76139025 -2.15366072]
 [-1.18164541 -0.84471025  0.38369433  0.21937084 -0.84149525]
 [ 0.84014711  2.22058366 -1.88895698 -1.97971284  1.06503851]
 [ 0.80850547 -0.91722305 -1.28738613 -1.36830142  0.25156219]
 [ 1.1430072   1.1193079  -1.49511273 -0.12182598  0.59615279]] 

[[3.         3.         3.         0.37258624 0.77987981]
 [3.         3. 

In [32]:
#If we want to save out python array as a text file we can also do that
np.savetxt('text_file_name.txt',rand_mat, delimiter = ',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter = ',')
print(rand_mat, '\n')
print(rand_mat_txt,'\n')

[[3.         3.         3.         0.37258624 0.77987981]
 [3.         3.         3.         0.         0.        ]
 [0.88163496 0.44024458 0.28692008 0.         0.        ]
 [0.32316457 0.57502597 0.16066403 0.69679869 0.3183468 ]
 [0.48129762 0.21583251 0.71351631 0.61757222 0.58746028]] 

[[3.         3.         3.         0.37258624 0.77987981]
 [3.         3.         3.         0.         0.        ]
 [0.88163496 0.44024458 0.28692008 0.         0.        ]
 [0.32316457 0.57502597 0.16066403 0.69679869 0.3183468 ]
 [0.48129762 0.21583251 0.71351631 0.61757222 0.58746028]] 

