# Panda examples
### Panda is package used to manage data
#### there are 2 data types in pandas 1: series 2: dataframes.A series a individual column of data frames, and dataframes are made up of bunch of series
#### pandas have SQL like fucntion for merging joining and sorting dataframes

### Panda series and data frames 2.5 :

In [1]:
import pandas as pd
import numpy as np #numpy is not necessary for for pandas but we will use some np code in examples
# in general it is a good practice to import all the packages at the begining

### Series:

In [2]:
# first lets look at series - think of this as a single column of spreadsheet(excel)
# Each entry in a series corresponds to a individual row in the spreadsheet
# we can create a series by converting list or numPy array

mylist = [5.4,6.1,1.7,99.8]
myarray = np.array(mylist)


In [3]:
#lets convert it into series

myseries1 = pd.Series(data = mylist)
print(myseries1,'\n')
print('===============\n')
myseries2 = pd.Series(data = myarray)
print(myseries2,'\n')

0     5.4
1     6.1
2     1.7
3    99.8
dtype: float64 


0     5.4
1     6.1
2     1.7
3    99.8
dtype: float64 



In [4]:
# we can access individual entries same like arrays and list
print(myseries1[2])

1.7


In [5]:
# we can add label to the entries
mylables = ['first','second','third','fourth']
myseries3 = pd.Series(data=mylist,index=mylables)
print(myseries3,'\n')

first      5.4
second     6.1
third      1.7
fourth    99.8
dtype: float64 



In [6]:
# We need not to define the data and index specifically
myseries4 = pd.Series(mylist,mylables)
print(myseries4)

first      5.4
second     6.1
third      1.7
fourth    99.8
dtype: float64


In [7]:
# we can access the values with lables

print(myseries4['third'])

1.7


In [8]:
#We can also perform math on series
myseries5 = pd.Series([5.5,1.1,8.8,1.6],['first','third','fourth','fifth'])
print(myseries5,'\n')
print(myseries5 + myseries4)

first     5.5
third     1.1
fourth    8.8
fifth     1.6
dtype: float64 

fifth       NaN
first      10.9
fourth    108.6
second      NaN
third       2.8
dtype: float64


In [9]:
# We can combine series to create a dataframe using concat() function

df1 = pd.concat([myseries4,myseries5],axis=1, sort=False)
df1

0    1
first    5.4  5.5
second   6.1  NaN
third    1.7  1.1
fourth  99.8  8.8
fifth    NaN  1.6

In [10]:
# We can create new dataframe with numPy Random

df2 = pd.DataFrame(np.random.randn(5,5))
df2

0         1         2         3         4
0 -0.533169  0.004821  1.083897 -1.214313  0.578110
1 -0.988463 -1.192778  0.152110 -0.253924 -0.118195
2 -1.982919 -1.694754 -0.573536  0.930857 -1.052697
3 -0.708297 -0.502602 -0.316509 -1.522313  0.031829
4 -0.308491  1.257667 -0.638208 -1.298033  0.831924

In [11]:
# lets provide labels to indexes

df3 = pd.DataFrame(np.random.randn(5,5),index=['first row','second row','third row','fourth row','fifth row'],columns=['first col','second col','third col','fourth col','fifth col'])
df3

first col  second col  third col  fourth col  fifth col
first row    1.068839   -1.342210  -1.233471   -0.322164  -0.476594
second row  -0.116631    0.204228  -0.045257   -0.005050   1.745439
third row    1.426130   -0.506310  -0.713814    1.076617   0.252079
fourth row   0.274096    0.175159   1.898978   -0.215322  -2.159483
fifth row    1.893106    0.269585   0.101587    0.969896   0.537304

### Pandas - Accessing and modifying 2.6 :

In [12]:
# We can access individual series in a dataframe
print(df3['second col'])

# lets access multiple series
df3[['second col','third col']]

first row    -1.342210
second row    0.204228
third row    -0.506310
fourth row    0.175159
fifth row     0.269585
Name: second col, dtype: float64


second col  third col
first row    -1.342210  -1.233471
second row    0.204228  -0.045257
third row    -0.506310  -0.713814
fourth row    0.175159   1.898978
fifth row     0.269585   0.101587

In [13]:
df3.loc['fourth row']

first col     0.274096
second col    0.175159
third col     1.898978
fourth col   -0.215322
fifth col    -2.159483
Name: fourth row, dtype: float64

In [14]:
df3.iloc[3]

first col     0.274096
second col    0.175159
third col     1.898978
fourth col   -0.215322
fifth col    -2.159483
Name: fourth row, dtype: float64

In [15]:
df3.loc[['third row','fourth row'],['second col','third col']]

second col  third col
third row    -0.506310  -0.713814
fourth row    0.175159   1.898978

In [16]:
df3 > 0 

first col  second col  third col  fourth col  fifth col
first row        True       False      False       False      False
second row      False        True      False       False       True
third row        True       False      False        True       True
fourth row       True        True       True       False      False
fifth row        True        True       True        True       True

In [17]:
print(df3[df3>0])

            first col  second col  third col  fourth col  fifth col
first row    1.068839         NaN        NaN         NaN        NaN
second row        NaN    0.204228        NaN         NaN   1.745439
third row    1.426130         NaN        NaN    1.076617   0.252079
fourth row   0.274096    0.175159   1.898978         NaN        NaN
fifth row    1.893106    0.269585   0.101587    0.969896   0.537304


In [18]:
# add column in dataframe
df3['sixth col'] = np.random.randn(5,1)
df3

## How to add row in dataframes??

first col  second col  third col  fourth col  fifth col  sixth col
first row    1.068839   -1.342210  -1.233471   -0.322164  -0.476594   0.345342
second row  -0.116631    0.204228  -0.045257   -0.005050   1.745439  -0.239587
third row    1.426130   -0.506310  -0.713814    1.076617   0.252079   1.355875
fourth row   0.274096    0.175159   1.898978   -0.215322  -2.159483  -0.070189
fifth row    1.893106    0.269585   0.101587    0.969896   0.537304   1.470098

In [19]:
# Remove column from dataframe
df3.drop('second col', axis=1)

first col  third col  fourth col  fifth col  sixth col
first row    1.068839  -1.233471   -0.322164  -0.476594   0.345342
second row  -0.116631  -0.045257   -0.005050   1.745439  -0.239587
third row    1.426130  -0.713814    1.076617   0.252079   1.355875
fourth row   0.274096   1.898978   -0.215322  -2.159483  -0.070189
fifth row    1.893106   0.101587    0.969896   0.537304   1.470098

In [20]:
df3
#Since we had dropped second col in above case but it is still present when asked
#drop is a function that returns dataframe, that does not change df3
#it just return something with second col removed
#if we want to get the changes that has removed second col we should store it into variable

first col  second col  third col  fourth col  fifth col  sixth col
first row    1.068839   -1.342210  -1.233471   -0.322164  -0.476594   0.345342
second row  -0.116631    0.204228  -0.045257   -0.005050   1.745439  -0.239587
third row    1.426130   -0.506310  -0.713814    1.076617   0.252079   1.355875
fourth row   0.274096    0.175159   1.898978   -0.215322  -2.159483  -0.070189
fifth row    1.893106    0.269585   0.101587    0.969896   0.537304   1.470098

In [21]:
df4 = df3.drop('second col', axis=1)
df4

#Now will get second col removed and set it in to dataframe df4

first col  third col  fourth col  fifth col  sixth col
first row    1.068839  -1.233471   -0.322164  -0.476594   0.345342
second row  -0.116631  -0.045257   -0.005050   1.745439  -0.239587
third row    1.426130  -0.713814    1.076617   0.252079   1.355875
fourth row   0.274096   1.898978   -0.215322  -2.159483  -0.070189
fifth row    1.893106   0.101587    0.969896   0.537304   1.470098

In [22]:
df5 = df3.drop('third row', axis=0)
df5

first col  second col  third col  fourth col  fifth col  sixth col
first row    1.068839   -1.342210  -1.233471   -0.322164  -0.476594   0.345342
second row  -0.116631    0.204228  -0.045257   -0.005050   1.745439  -0.239587
fourth row   0.274096    0.175159   1.898978   -0.215322  -2.159483  -0.070189
fifth row    1.893106    0.269585   0.101587    0.969896   0.537304   1.470098

In [23]:
# We can remove index in dataframe
# here reset_index() is also a function that returns dataframe, and this won't affect df5
df5.reset_index()

# now in below case index is not like index anymore it bacame column index with values like 
#first row, second row etc.

index  first col  second col  third col  fourth col  fifth col  \
0   first row   1.068839   -1.342210  -1.233471   -0.322164  -0.476594   
1  second row  -0.116631    0.204228  -0.045257   -0.005050   1.745439   
2  fourth row   0.274096    0.175159   1.898978   -0.215322  -2.159483   
3   fifth row   1.893106    0.269585   0.101587    0.969896   0.537304   

   sixth col  
0   0.345342  
1  -0.239587  
2  -0.070189  
3   1.470098

In [24]:
df5

# here reset_index() is also a function that returns dataframe, and this won't affect df5

first col  second col  third col  fourth col  fifth col  sixth col
first row    1.068839   -1.342210  -1.233471   -0.322164  -0.476594   0.345342
second row  -0.116631    0.204228  -0.045257   -0.005050   1.745439  -0.239587
fourth row   0.274096    0.175159   1.898978   -0.215322  -2.159483  -0.070189
fifth row    1.893106    0.269585   0.101587    0.969896   0.537304   1.470098

In [25]:
# by setting inplace=True we are saying to python after reset index save the result to df5
# hence after making inplace=True in code df5 gets modified

df5.reset_index(inplace=True)
df5

index  first col  second col  third col  fourth col  fifth col  \
0   first row   1.068839   -1.342210  -1.233471   -0.322164  -0.476594   
1  second row  -0.116631    0.204228  -0.045257   -0.005050   1.745439   
2  fourth row   0.274096    0.175159   1.898978   -0.215322  -2.159483   
3   fifth row   1.893106    0.269585   0.101587    0.969896   0.537304   

   sixth col  
0   0.345342  
1  -0.239587  
2  -0.070189  
3   1.470098

In [26]:
df5['new name'] = ['This','is','The','Row']
df5

index  first col  second col  third col  fourth col  fifth col  \
0   first row   1.068839   -1.342210  -1.233471   -0.322164  -0.476594   
1  second row  -0.116631    0.204228  -0.045257   -0.005050   1.745439   
2  fourth row   0.274096    0.175159   1.898978   -0.215322  -2.159483   
3   fifth row   1.893106    0.269585   0.101587    0.969896   0.537304   

   sixth col new name  
0   0.345342     This  
1  -0.239587       is  
2  -0.070189      The  
3   1.470098      Row

In [27]:
df5.set_index('new name',inplace=True)
df5

index  first col  second col  third col  fourth col  fifth col  \
new name                                                                        
This       first row   1.068839   -1.342210  -1.233471   -0.322164  -0.476594   
is        second row  -0.116631    0.204228  -0.045257   -0.005050   1.745439   
The       fourth row   0.274096    0.175159   1.898978   -0.215322  -2.159483   
Row        fifth row   1.893106    0.269585   0.101587    0.969896   0.537304   

          sixth col  
new name             
This       0.345342  
is        -0.239587  
The       -0.070189  
Row        1.470098

### Combining data frames 2.7
#### It is almost similar to SQL. to combine dataframes
3 methods 
1. concat 
2. join 
3. merge

### concat :

In [28]:
df7 = pd.DataFrame({'customer' :['101','102','103','108'],
                    'category' :['cat2','cat2','cat1','cat4'],
                    'important':['yes','no','yes','yes'],
                    'sales'    :[125,12,214,663]},index=[0,1,2,3])
df7

customer category important  sales
0      101     cat2       yes    125
1      102     cat2        no     12
2      103     cat1       yes    214
3      108     cat4       yes    663

In [29]:
df8 = pd.DataFrame({'customer' :['103','108','109','110'],
                    'color'    :['blue','white','blue','pink'],
                    'distance' :[13,56,78,97],
                    'sales'    :[125,12,214,663]},index=[4,5,6,7])
df8

customer  color  distance  sales
4      103   blue        13    125
5      108  white        56     12
6      109   blue        78    214
7      110   pink        97    663

In [30]:
pd.concat([df7,df8],axis=0,sort=False)

# df7 and df8 stack on each other for axis = 0

customer category important  sales  color  distance
0      101     cat2       yes    125    NaN       NaN
1      102     cat2        no     12    NaN       NaN
2      103     cat1       yes    214    NaN       NaN
3      108     cat4       yes    663    NaN       NaN
4      103      NaN       NaN    125   blue      13.0
5      108      NaN       NaN     12  white      56.0
6      109      NaN       NaN    214   blue      78.0
7      110      NaN       NaN    663   pink      97.0

In [31]:
pd.concat([df7,df8],axis=0,sort=True)

category  color customer  distance important  sales
0     cat2    NaN      101       NaN       yes    125
1     cat2    NaN      102       NaN        no     12
2     cat1    NaN      103       NaN       yes    214
3     cat4    NaN      108       NaN       yes    663
4      NaN   blue      103      13.0       NaN    125
5      NaN  white      108      56.0       NaN     12
6      NaN   blue      109      78.0       NaN    214
7      NaN   pink      110      97.0       NaN    663

In [32]:
pd.concat([df7,df8],axis=1,sort=False)

# df7 and df8 are side by side of each other for axis = 1
# concat works on indexes

customer category important  sales customer  color  distance  sales
0      101     cat2       yes  125.0      NaN    NaN       NaN    NaN
1      102     cat2        no   12.0      NaN    NaN       NaN    NaN
2      103     cat1       yes  214.0      NaN    NaN       NaN    NaN
3      108     cat4       yes  663.0      NaN    NaN       NaN    NaN
4      NaN      NaN       NaN    NaN      103   blue      13.0  125.0
5      NaN      NaN       NaN    NaN      108  white      56.0   12.0
6      NaN      NaN       NaN    NaN      109   blue      78.0  214.0
7      NaN      NaN       NaN    NaN      110   pink      97.0  663.0

### Merge and Join :
    1. Merge combines dataframes using a column values to identify column entries
    2. join combines dataframes using the index to identify common entries

In [33]:
pd.merge(df7,df8, how='outer',on='customer') # outer merge is union of on

#if any column has same name will be appeneded with _x and _y unless it is in 'on'

customer category important  sales_x  color  distance  sales_y
0      101     cat2       yes    125.0    NaN       NaN      NaN
1      102     cat2        no     12.0    NaN       NaN      NaN
2      103     cat1       yes    214.0   blue      13.0    125.0
3      108     cat4       yes    663.0  white      56.0     12.0
4      109      NaN       NaN      NaN   blue      78.0    214.0
5      110      NaN       NaN      NaN   pink      97.0    663.0

In [34]:
pd.merge(df7,df8, how='inner',on='customer') # inner merge is union of on

customer category important  sales_x  color  distance  sales_y
0      103     cat1       yes      214   blue        13      125
1      108     cat4       yes      663  white        56       12

In [35]:
pd.merge(df7,df8, how='left',on='customer') # like left outer join in SQL

# show all the records of left table

customer category important  sales_x  color  distance  sales_y
0      101     cat2       yes      125    NaN       NaN      NaN
1      102     cat2        no       12    NaN       NaN      NaN
2      103     cat1       yes      214   blue      13.0    125.0
3      108     cat4       yes      663  white      56.0     12.0

In [36]:
pd.merge(df7,df8, how='right',on='customer') # like right outer join in SQL

# show all the records of right table

customer category important  sales_x  color  distance  sales_y
0      103     cat1       yes    214.0   blue        13      125
1      108     cat4       yes    663.0  white        56       12
2      109      NaN       NaN      NaN   blue        78      214
3      110      NaN       NaN      NaN   pink        97      663

### Join :

    1. It is very much similar to Merge but here in join we use index instead of column

In [37]:
# Merge combines on column values
# Join combines on index values

df9 = pd.DataFrame({'Q1':[101,102,103],
                    'Q2':[201,202,203]},index=['I0','I1','I2'])

df10 = pd.DataFrame({'Q3':[301,302,303],
                    'Q4':[401,402,403]},index=['I0','I2','I3'])

In [38]:
df9.join(df10,how='outer')

Q1     Q2     Q3     Q4
I0  101.0  201.0  301.0  401.0
I1  102.0  202.0    NaN    NaN
I2  103.0  203.0  302.0  402.0
I3    NaN    NaN  303.0  403.0

In [39]:
df9.join(df10,how='inner')

Q1   Q2   Q3   Q4
I0  101  201  301  401
I2  103  203  302  402

In [40]:
df9.join(df10,how='left')

Q1   Q2     Q3     Q4
I0  101  201  301.0  401.0
I1  102  202    NaN    NaN
I2  103  203  302.0  402.0

In [41]:
df9.join(df10,how='right')

Q1     Q2   Q3   Q4
I0  101.0  201.0  301  401
I2  103.0  203.0  302  402
I3    NaN    NaN  303  403

### Pandas Functions 2.8 :

In [42]:
df8['color'].unique()

array(['blue', 'white', 'pink'], dtype=object)

In [43]:
df8['color'].value_counts()

blue     2
white    1
pink     1
Name: color, dtype: int64

In [44]:
df9.mean()

Q1    102.0
Q2    202.0
dtype: float64

In [45]:
df8.columns

Index(['customer', 'color', 'distance', 'sales'], dtype='object')

In [46]:
df8

customer  color  distance  sales
4      103   blue        13    125
5      108  white        56     12
6      109   blue        78    214
7      110   pink        97    663

In [47]:
new_df = df8[(df8['customer'] != 109) & (df8['color'] != 'blue') ]
new_df

customer  color  distance  sales
5      108  white        56     12
7      110   pink        97    663

In [48]:
print(df8['sales'].mean())
print(df8['distance'].min())
print(df8['customer'].max())
print(df8['distance'].std()) 
print(df8['distance'].sum())



253.5
13
110
36.12016980395672
244


In [49]:
# Creating custom function

def profit(s):
    return s * 0.5


In [50]:
df8['sales'].apply(profit)

4     62.5
5      6.0
6    107.0
7    331.5
Name: sales, dtype: float64

In [51]:
df8['color'].apply(len)

4    4
5    5
6    4
7    4
Name: color, dtype: int64

In [52]:
# applymap is used to apply every entry in DataFrame
# applymap works only in DataFrames, always does it entry by entry

df11 = df8[['distance','sales']]
df11.applymap(profit)


distance  sales
4       6.5   62.5
5      28.0    6.0
6      39.0  107.0
7      48.5  331.5

In [53]:
def col_sum(co):
    return sum(co)
df11.apply(col_sum)

distance     244
sales       1014
dtype: int64

In [54]:
del df8['color']
df8

customer  distance  sales
4      103        13    125
5      108        56     12
6      109        78    214
7      110        97    663

In [55]:
df8.index

Int64Index([4, 5, 6, 7], dtype='int64')

In [56]:
df8.sort_values(by='distance',inplace=True)
df8

customer  distance  sales
4      103        13    125
5      108        56     12
6      109        78    214
7      110        97    663

In [58]:
df8

customer  distance  sales
4      103        13    125
5      108        56     12
6      109        78    214
7      110        97    663

In [62]:
#similar to numpy we can save the Excel

df8.to_csv('df8.csv',index=True)

In [71]:
new_df8 = pd.read_csv('df8.csv',index_col=0)
new_df8

customer  distance  sales
4       103        13    125
5       108        56     12
6       109        78    214
7       110        97    663

In [74]:
df8.to_excel('df8.xlsx',index=False,sheet_name='First sheet')

In [82]:
newer_df8 = pd.read_excel('df8.xlsx',sheet_name='First sheet', index_col=0)
newer_df8

distance  sales
customer                 
103             13    125
108             56     12
109             78    214
110             97    663

In [83]:
demo_array=np.arange(0,10)
demo_array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
demo_array <3


array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [85]:
demo_array[demo_array <6]


array([0, 1, 2, 3, 4, 5])

In [87]:
np.max(demo_array)

9

In [89]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix

array([[13, 35, 74, 48],
       [23, 37, 37, 38],
       [73, 39, 93, 39]])

In [92]:
demo_matrix[:, (1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [94]:
demo_matrix[2,3]

39

In [95]:
demo_array = np.arange(10,21)

What is the output of the following lines?

subset_demo_array = demo_array[0:7]

subset_demo_array[:]= 101

subset_demo_array

Object `lines` not found.


array([101, 101, 101, 101, 101, 101, 101])

In [97]:
test_array = [10, 11.5, 12, 13.5, 14,15]
test_array[2:3]

[12]

In [98]:
list_l =[[12,34,55,],[66,45,77],[45,77,88]]

np.array(list_l)

array([[12, 34, 55],
       [66, 45, 77],
       [45, 77, 88]])

In [99]:
score = [10, 15, 20, 25]

pd.Series(data=score, index = ['a','b','c','d'])

a    10
b    15
c    20
d    25
dtype: int64

In [100]:
data = {'prodID': ['101', '102', '103', '104', '104'],

                    'prodname': ['X', 'Y', 'Z', 'X', 'W'],

                     'profit': ['2738', '2727', '3497', '7347', '3743']}
data

{'prodID': ['101', '102', '103', '104', '104'],
 'prodname': ['X', 'Y', 'Z', 'X', 'W'],
 'profit': ['2738', '2727', '3497', '7347', '3743']}

In [101]:
dataframe = pd.DataFrame(data)
dataframe

prodID prodname profit
0    101        X   2738
1    102        Y   2727
2    103        Z   3497
3    104        X   7347
4    104        W   3743

In [102]:
grouped_data = dataframe.groupby('prodID')
grouped_data

In [103]:
grouped_data.max()

prodname profit
prodID                
101           X   2738
102           Y   2727
103           Z   3497
104           X   7347